image: debian:buster

stages:
  - build
  - test
  - deploy

before_script:
  - apt update -y
  - apt install -y automake bison bsdmainutils build-essential flex git libssl-dev libtool openssl rsync ssh sudo zlib1g-dev

build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --enable-openssl --enable-oper-chghost --with-nicklen=50 --with-topiclen=390 --with-custom-branding=Upnet --program-transform-name='s/^charybdis-/cherry-/;s/^charybdis$/cherry/' --prefix=/usr/ircd
    - make
  artifacts:
    paths:
      - Makefile
      - aclocal.m4
      - authd
      - bandb
      - config.status
      - configure
      - doc
      - extensions
      - help
      - include
      - ircd
      - libltdl
      - librb
      - libtool
      - m4
      - modules
      - ssld
      - tests
      - tools
      - wsockd

test:
  stage: test
  script:
    - chown -R irc "$CI_PROJECT_DIR"
    - sudo -u irc make -C tests check-local

deploy:
  stage: deploy
  script:
    - mkdir -p /usr/ircd
    - make install
    - tar -C "/usr/ircd" -czf "/tmp/$CI_BUILD_TAG.tar.gz" .
    - chmod 600 "$SSH_PRIVATE_KEY"
    - rsync -e "ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no" -av "/tmp/$CI_BUILD_TAG.tar.gz" "nginx@watson.naughtysysadmins.com:"
  rules:
    - if: '$CI_BUILD_TAG =~ /^v[0-9]+(\.[0-9]+)+$/'
      when: always



