image: debian:buster

stages:
  - build
  - test
  - deploy

before_script:
  - apt update -y
  - apt install -y automake bison bsdmainutils build-essential flex git openssl libssl-dev libtool zlib1g-dev

build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --enable-openssl --with-nicklen=50
    - make

test:
  stage: test
  image:
    name: debian:buster
    entrypoint:
      - exec
      - su
      - -c
      - /bin/bash
      - irc
  script:
    - ./autogen.sh
    - ./configure --enable-openssl --with-nicklen=50
    - make
    - make -C tests check-local
