image: debian:buster

stages:
  - build
  - test
  - deploy

before_script:
  - apt update -y
  - apt install -y automake bison bsdmainutils build-essential flex git libssl-dev libtool openssl sudo zlib1g-dev

build:
  stage: build
  script:
    - ./autogen.sh
    - ./configure --enable-openssl --with-nicklen=50
    - make

test:
  stage: test
  image:
    name: debian:buster
  script:
    - ./autogen.sh
    - ./configure --enable-openssl --with-nicklen=50
    - make
    - chown -R irc "$CI_PROJECT_DIR"
    - sudo -u irc make -C tests check-local
